const BOM_KEY="panasonic-selector-shared-bom-v1";
const frame=document.getElementById("selectorFrame");
const rows=document.getElementById("bomRows");
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
function readItems(){try{const items=JSON.parse(localStorage.getItem(BOM_KEY)||"[]");return Array.isArray(items)?items:[]}catch{return[]}}
let items=readItems();
function writeItems(){localStorage.setItem(BOM_KEY,JSON.stringify(items))}
function renderBom(){if(!items.length){rows.innerHTML='<tr><td class="empty" colspan="6">尚未加入詢價項目。</td></tr>';return}rows.innerHTML=items.map((item,index)=>`<tr><td>${escapeHtml(item.category)}</td><td>${escapeHtml(item.model)}</td><td>${escapeHtml(item.spec)}</td><td><input type="number" min="1" step="1" value="${Math.max(1,Number(item.qty)||1)}" data-qty="${index}" aria-label="數量"></td><td><input value="${escapeHtml(item.note)}" data-note="${index}" aria-label="備註"></td><td><button data-delete="${index}" type="button">刪除</button></td></tr>`).join("")}
function addItem(product){const spec=[product.type,product.subtype,product.distance&&`檢測距離 ${product.distance}`,product.output,product.action&&`輸出動作 ${product.action}`].filter(Boolean).join(" / ");const key=`光電感測器|${product.model}|${spec}|`;const existing=items.find(item=>item.key===key);if(existing)existing.qty=(Number(existing.qty)||1)+1;else items.push({key,category:"光電感測器",model:product.model,spec,qty:1,note:""});writeItems();renderBom()}
function decorateFrame(){try{const doc=frame.contentDocument;if(!doc)return;let style=doc.getElementById("sharedBomBridgeStyle");if(!style){style=doc.createElement("style");style.id="sharedBomBridgeStyle";style.textContent=".shared-bom-bridge-button{border:1px solid #b8c9d9!important;border-radius:4px!important;background:#fff!important;color:#075d9d!important;padding:7px 9px!important;cursor:pointer;font-size:12px;font-weight:600}.shared-bom-bridge-button:hover{background:#eaf4fb!important}";doc.head.append(style)}doc.querySelectorAll("#productGrid .card").forEach(card=>{const footer=card.querySelector(".card-foot");const detail=card.querySelector("[data-detail]");if(!footer||!detail||footer.querySelector(".shared-bom-bridge-button"))return;const button=doc.createElement("button");button.type="button";button.className="shared-bom-bridge-button";button.textContent="加入共用 BOM";button.addEventListener("click",event=>{event.preventDefault();event.stopPropagation();const data=frame.contentWindow.PHOTOELECTRIC_DATA;const product=data?.products?.find(item=>item.id===detail.dataset.detail);if(product)addItem(product)});footer.insertBefore(button,footer.lastElementChild)});syncFrameHeight()}catch{}}
function syncFrameHeight(){try{const doc=frame.contentDocument;if(doc)frame.style.height=`${Math.max(680,doc.documentElement.scrollHeight+8)}px`}catch{}}
frame.addEventListener("load",()=>{decorateFrame();const doc=frame.contentDocument;new MutationObserver(()=>{decorateFrame();syncFrameHeight()}).observe(doc.body,{childList:true,subtree:true});new ResizeObserver(syncFrameHeight).observe(doc.body);setTimeout(syncFrameHeight,500)});
rows.addEventListener("input",event=>{const qty=event.target.closest("[data-qty]"),note=event.target.closest("[data-note]");if(qty){const item=items[Number(qty.dataset.qty)];item.qty=Math.max(1,Number(qty.value)||1);qty.value=item.qty;writeItems()}if(note){items[Number(note.dataset.note)].note=note.value;writeItems()}});
rows.addEventListener("click",event=>{const button=event.target.closest("[data-delete]");if(button){items.splice(Number(button.dataset.delete),1);writeItems();renderBom()}});
document.getElementById("exportBom").addEventListener("click",()=>{const csvRows=[["類別","型號","規格","數量","備註"],...items.map(item=>[item.category,item.model,item.spec,item.qty,item.note||""])];const csv="\ufeff"+csvRows.map(row=>row.map(value=>`"${String(value??"").replace(/"/g,'""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="Panasonic_共用BOM.csv";link.click();URL.revokeObjectURL(url)});
window.addEventListener("storage",event=>{if(event.key===BOM_KEY){items=readItems();renderBom()}});
renderBom();
